import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — StudioStack',
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-sm text-neutral-500 mb-8">Last updated: March 2026</p>

      <div className="space-y-8">
        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            1. Acceptance of Terms
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            By accessing or using StudioStack (&quot;the Platform&quot;), you
            agree to be bound by these Terms of Service (&quot;Terms&quot;). If
            you do not agree to these Terms, you may not access or use the
            Platform. These Terms constitute a legally binding agreement between
            you and StudioStack (Pty) Ltd (&quot;StudioStack&quot;,
            &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            2. Description of Service
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            StudioStack is an AI-powered content generation platform that
            enables users to create written content, marketing copy, and other
            text-based materials using artificial intelligence. The Platform
            operates on a per-credit pricing model, whereby users purchase
            credit packs and expend credits to generate content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            3. User Accounts
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            To use the Platform, you must register for an account. You agree to
            provide accurate, current, and complete information during
            registration and to keep your account information updated. You are
            solely responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            You must be at least 18 years of age to create an account and use
            the Platform. By registering, you represent and warrant that you
            meet this age requirement.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            4. Credits and Payments
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            StudioStack operates on a credit-based system. Credits are
            purchased in predefined packs and are used to generate content on
            the Platform. The following terms apply to credits and payments:
          </p>
          <ul className="list-disc pl-6 text-neutral-300 space-y-2">
            <li>
              Credits are generally non-refundable, except as outlined in our
              Refund Policy.
            </li>
            <li>
              Purchased credits do not expire and remain available in your
              account until used.
            </li>
            <li>
              Pricing for credit packs is subject to change. We will provide
              reasonable notice of any pricing changes, and such changes will
              not affect credits already purchased.
            </li>
            <li>
              All payments are processed through our third-party payment
              providers (PayFast and PayPal). We do not store your payment card
              details.
            </li>
            <li>
              You are responsible for any applicable taxes associated with your
              purchases.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            5. Content Generation
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            Content produced through the Platform is generated by artificial
            intelligence. While we strive to provide high-quality outputs, you
            acknowledge and agree that:
          </p>
          <ul className="list-disc pl-6 text-neutral-300 space-y-2">
            <li>
              AI-generated content may contain inaccuracies, errors, or
              omissions. We make no guarantee regarding the accuracy,
              completeness, or suitability of generated content.
            </li>
            <li>
              You are solely responsible for reviewing, editing, and verifying
              all generated content before use.
            </li>
            <li>
              StudioStack is not liable for any consequences arising from the
              use of AI-generated content without proper review.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            6. Intellectual Property
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            You retain full ownership of all content generated through the
            Platform using your credits. You are free to use, modify,
            distribute, and commercialise your generated content without
            restriction.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            StudioStack retains all rights, title, and interest in the
            Platform itself, including but not limited to its software,
            algorithms, user interface, design, branding, documentation, and
            all associated intellectual property. Nothing in these Terms grants
            you any right to the Platform&apos;s underlying technology.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            7. Acceptable Use
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            You agree not to use the Platform for any of the following
            purposes:
          </p>
          <ul className="list-disc pl-6 text-neutral-300 space-y-2">
            <li>
              Generating content that is illegal, defamatory, obscene, or
              otherwise unlawful under applicable law.
            </li>
            <li>
              Creating content intended to harass, threaten, intimidate, or
              harm any individual or group.
            </li>
            <li>
              Producing bulk unsolicited content (spam) or content intended to
              deceive or mislead.
            </li>
            <li>
              Attempting to reverse engineer, decompile, disassemble, or
              otherwise derive the source code or underlying algorithms of the
              Platform.
            </li>
            <li>
              Circumventing or attempting to circumvent any access controls,
              rate limits, or security measures of the Platform.
            </li>
            <li>
              Using the Platform in any manner that could damage, disable, or
              impair its operation.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            8. Limitation of Liability
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            The Platform is provided on an &quot;as is&quot; and &quot;as
            available&quot; basis, without warranties of any kind, whether
            express, implied, or statutory. To the maximum extent permitted by
            applicable law, StudioStack disclaims all warranties, including
            but not limited to implied warranties of merchantability, fitness
            for a particular purpose, and non-infringement.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            In no event shall StudioStack&apos;s total liability to you for
            all claims arising out of or relating to the use of the Platform
            exceed the total amount you have paid to StudioStack in the twelve
            (12) months preceding the event giving rise to the claim.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            9. Termination
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            We reserve the right to suspend or terminate your account at any
            time if you violate these Terms or engage in conduct that we
            determine, in our sole discretion, to be harmful to the Platform
            or other users. Upon termination for cause, any remaining credits
            in your account will be forfeited.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            You may delete your account at any time through your account
            settings. Upon voluntary account deletion, your personal data will
            be removed in accordance with our Privacy Policy.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            10. Governing Law
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            These Terms shall be governed by and construed in accordance with
            the laws of the Republic of South Africa. Any disputes arising
            from or in connection with these Terms shall be subject to the
            exclusive jurisdiction of the courts of South Africa.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">
            11. Changes to Terms
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            We may update these Terms from time to time. We will notify you of
            any material changes by posting the revised Terms on the Platform
            and updating the &quot;Last updated&quot; date at the top of this
            page. We will provide at least thirty (30) days&apos; notice before
            any material changes take effect. Your continued use of the
            Platform after the effective date of the revised Terms constitutes
            your acceptance of the changes.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">12. Contact Us</h2>
          <p className="text-neutral-300 leading-relaxed">
            If you have any questions or concerns regarding these Terms of
            Service, please contact us at{' '}
            <a
              href="mailto:legal@studiostack.com"
              className="text-white underline underline-offset-4 hover:text-neutral-300 transition-colors"
            >
              legal@studiostack.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
